---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-13 15:05
---

local MapReader = require("io.MapReader")
print(string.match('a1cd', '%d'))
MapReader.parse(arg[1])