---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-17 11:03
---

local M = {}

M.printMap = function(map)
    for i = 1, #map do
        local line = {}
        for j = 1, #map[i] do
            table.insert(line, map[i][j])
        end
        print(table.unpack(line))
    end
end

return M