---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
---

local M = {}

M.printMap = function(map, rowHints, colHints)
    local space = '   '
    local borderTop = space .. '_' .. string.rep("__", #map)
    local borderBottom = space .. '¯' .. string.rep("¯", #map * 2)
    local count = 1
    local bottom = ""
    print(borderTop)
    for row = 1, #map do
        local toPrint = ""
        for col = 1, #map do
            toPrint = toPrint .. map[row][col] .. " "
        end
        print(rowHints[count] .. " | " .. toPrint .. '|')
        bottom = bottom .. colHints[count] .. " "
        count = count + 1
    end
    print(borderBottom)
    print(space .. ' ' .. bottom .. ' ')
end

return M