---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-13 15:04
---

local json = require('utils.json')
local MapUtils = require('utils.MapUtils')
local MapPrinter = require('io.MapPrinter')
local Cell = require('entities.Cell')
local CellType = require('entities.CellType')

local M = {}

local function tryReadJsonMap(path)
    local file = assert(io.open(path, 'rb'), string.format('Unable to open file :: %s', path))
    local content = file:read('*all')
    file:close()
    return content
end

local decodeJsonMap = function(path)
    return json.decode(tryReadJsonMap(path))
end

M.parse = function(path)
    local decodedJson = decodeJsonMap(path)
    local mapDimension = MapUtils.getMapDimension(decodedJson)
    local map = MapUtils.getMap(decodedJson, mapDimension)
    local topHints = MapUtils.getTopHints(decodedJson, mapDimension)
    local leftHints = MapUtils.getLeftHints(decodedJson, mapDimension)

    print(table.unpack(leftHints))
    print(table.unpack(topHints))
    MapPrinter.printMap(map)

    cell = Cell:create(1, 2)
    cell2 = Cell:create(2, 1)
    print(cell:getRow())
    print(cell:getType())
    print(CellType.toString(cell:getType()))
    print(cell2:getRow())
end

return M