---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-17 15:33
---

local constants = require('entities.Constants')

local M = {}

M.unknown = function()
    return constants.cellTypes.unknown
end
M.tent = function()
    return constants.cellTypes.tent
end
M.uncertain = function()
    return constants.cellTypes.uncertain
end
M.grass = function()
    return constants.cellTypes.grass
end
M.tree = function()
    return constants.cellTypes.tree
end

M.toString = function(type)
    if type == 0 then
        return 'unknown'
    elseif type == 1 then
        return 'tent'
    elseif type == 2 then
        return 'uncertain'
    elseif type == 3 then
        return 'grass'
    elseif type == 4 then
        return 'tree'
    else
        return 'wrong type'
    end
end

return M