---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-17 14:37
---

local M = {}

function protect(tbl)
    return setmetatable({}, {
        __index = tbl,
        __newindex = function(t, key, value)
            error("attempting to change constant " ..
                    tostring(key) .. " to " .. tostring(value), 2)
        end
    })
end

M.cellTypes = protect({
    unknown = 0,
    tent = 1,
    uncertain = 2,
    grass = 3,
    tree = 4
})

return M
