---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-18 14:52
---

--[[
class MapSnapshot {
    constructor(changedCells, map, isValid, isSolved, message) {
        this._changedCells = changedCells;
this._map = (map == null || map == undefined) ? null : DeepCopyMap(map);
this._isValid = isValid;
this._isSolved = isSolved;
this._message = message;
}

get changedCells() {
return this._changedCells;
}

get map() {
return this._map;
}

get isValid() {
return this._isValid;
}

get isSolved() {
return this._isSolved;
}
}]]

MapState = {}
MapState.__index = MapState

function MapState:create(changed, map, valid, solved, msg)
    local state = {}
    setmetatable(state, MapState)
    self.changed = changed
    self.map = map
    self.valid = valid
    self.solved = solved
    self.msg = msg
    return state
end

function MapState:getChangedCells()
    return self.changed
end

function MapState:getMap()
    return self.map
end

function MapState:isValid()
    return self.valid
end

function MapState:isSolved()
    return self.solved
end

return MapState
