---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
---
local NumberUtils = require('utils.NumberUtils')
local StringUtils = require('utils.StringUtils')

local M = {}

M.getMapDimension = function(decodedJson)
    return assert(decodedJson['dimension'], 'Map dimension not specified!')
end

local getMapHeight = function(decodedJson)
    return assert(#decodedJson['map'], 'Map not specified!')
end

M.getColHints = function(decodedJson, mapDimension)
    local hints = assert(decodedJson['colHints'], 'Col Hints not specified!')
    for _, v in ipairs(hints) do
        assert(NumberUtils.isInt(v) and NumberUtils.isBetween(v, 0, mapDimension))
    end
    return #hints == mapDimension and hints or error('Col hints length should be same as map dimension')
end

M.getRowHints = function(decodedJson, mapDimension)
    local hints = assert(decodedJson['rowHints'], 'Row Hints not specified!')
    for _, v in ipairs(hints) do
        assert(NumberUtils.isInt(v) and NumberUtils.isBetween(v, 0, mapDimension))
    end
    return #hints == mapDimension and hints or error('Row hints length should be same as map dimension')
end

M.getMap = function(decodedJson, mapDimension)
    local mapHeight = getMapHeight(decodedJson)
    -- check whether the map dimension is correct
    assert(mapDimension == mapHeight,
            string.format('Invalid map height :: found %d | should be %d',
                    mapHeight,
                    mapDimension)
    )
    local map = {}
    for i = 1, mapDimension do
        -- check whether map is squared
        assert(#decodedJson['map'][i] == mapDimension, 'Map width and height should be the same!')
        local mapLine = {}
        for j = 1, #decodedJson['map'][i] do
            local currentValue = decodedJson['map'][i][j]
            assert(StringUtils.isValidChar(currentValue))
            table.insert(mapLine, currentValue)
        end
        table.insert(map, mapLine)
    end -- for i = 1, mapDimension
    return map
end

M.stringifyMap = function(map)
    local result = ''
    if not map then
        return
    end
    for row = 1, #map do
        for col = 1, #map do
            result = result .. map[row][col]
        end
        result = result .. '\n'
    end
    return result
end

return M