---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-14 11:17
---

local M = {}

M.isInt = function(n)
    return ((type(n) == "number") and (math.floor(n) == n)) and true or error(string.format('%s is not a number', n))
end

M.isBinary = function(number)
    return (number <= 1 and number >= 0) and true or error(string.format('Only 0 or 1 is allowed for the map field :: found %d', number))
end

return M

