---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-14 11:17
---

local M = {}

M.isInt = function(n)
    return (type(n) == "number") and (math.floor(n) == n)
end

return M

