---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-13 17:36
---

local M = {}

function M.split(string, pattern)
    local result = {}
    string:gsub(pattern, function(x)
        result[#result + 1] = x
    end)
    return result
end

return M