---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
---

local M = {}

function M.split(string, pattern)
    local result = {}
    string:gsub(pattern, function(x)
        result[#result + 1] = x
    end)
    return result
end

M.isValidChar = function(char)
    return (char == 'T' or char == '?') and true or error('Only T and ? are allowed as characters for map representation')
end

return M