---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
--- DateTime: 2019-06-17 18:37
---

local M = {}

M.clone = function(source)
    return {table.unpack(source)}
end

return M