---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by c0ntrast3d.
---

local fOp = require('utils.FunctionalOperators')
local NumberUtils = require('utils.NumberUtils')

local M = {}

M.initCounts = function(dimension)
    local colCount, rowCount = {}, {}
    for counter = 1, dimension do
        table.insert(colCount, 0)
        table.insert(rowCount, 0)
    end
    return rowCount, colCount
end

--[[for row = 1, #map do
    if map[row][y] == 'T' or map[row][y] == "." or map[row][y] == "▲" then
        totalColOccupants = totalColOccupants + 1
    end
end

if #map - totalColOccupants == colHints[ncol] then
    for i = 1, #map do
        if (map[i][y] == "?") then
            map[i][y] = "▲"
        end
    end
    if (colHints[y] == colTentCount[y]) then
        for i = 1, #map do
            if (map[i][y] == "?") then
                map[i][y] = "."
            end
        end
    end
end]]

return M